## Basic Configuration

baseurl = "https://www.busrakoken.com/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Busra Koken"
title = "Busra Koken"

theme = "hugo-goa"

## Hugo Built-in Features
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Busra Koken"
intro = "Site Reliability | Infrastrucure | DevOps"
description = "Passionate SRE with obsessions about DevOps engineering culture(real one), automation, documentation, diversity and mental health. Also insterested in photography, psyhcology, writing and public speaking."
#description = "Currently [@trivago](https://www.trivago.com/). Blogger, Photographer. Learning, discovering, collecting stories every single day — sometimes I give talks about them."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
linkedin = "busrakoken"
github = "busrakoken"
instagram = "busrakoken"
twitter = "busrakoken"
email = "busrakoken@gmail.com"

## Extras
[params.extra]
copyright = "© 2021. Busra Koken. [Some Rights Reserved](https://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
hightlightjs = true

[[menu.main]]
    name = "Conference talks"
    identifier = "talks"
    weight = 200
    url = "/talks/"